#!/usr/bin/env bash
# Install the optional extras (AUR via paru): apps and the lidm login manager with its theme.
# Usage: ./install-extras.sh [--dry-run]
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
parse_args "$@"
ensure_paru

# Apps: tlock (2FA tokens TUI), xleak (Excel viewer TUI), tabiew (CSV viewer TUI),
# spotify (shown in waybar), onlyoffice, zed
run paru -S --needed tlock xleak-bin tabiew spotify onlyoffice-bin zed

# Cursor (if installed): the Wal Theme extension, so the editor follows the desktop
# theme (it reads ~/.cache/wal/colors.json and updates when it changes). Pick it once
# in Cursor: Ctrl+K Ctrl+T -> "Wal". Extensions never touch Cursor's chats or data.
if command -v cursor >/dev/null; then
    run cursor --install-extension dlasagno.wal-theme
fi

# lidm needs a service provider; EndeavourOS uses systemd. It is installed
# first so paru never asks which provider of lidm-service to use.
service_provider=lidm-systemd

run paru -S --needed "$service_provider"
run paru -S --needed lidm

# Theme; the existing config is kept as /etc/lidm.ini.bak
repo=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
run sudo install -b -S .bak -m 644 "$repo/lidm/lidm.ini" /etc/lidm.ini

# Console: a bigger font with box-drawing characters, and the pywal colours as its
# 16-colour palette (loaded by a lidm.service drop-in, regenerated by theme.sh)
run paru -S --needed terminus-font
if grep -q '^FONT=' /etc/vconsole.conf 2>/dev/null; then
    run sudo sed -i 's/^FONT=.*/FONT=ter-v28n/' /etc/vconsole.conf
else
    run sudo sh -c 'echo FONT=ter-v28n >> /etc/vconsole.conf'
fi
run "$repo/hypr/scripts/vt-palette.sh"
run sudo mkdir -p /etc/systemd/system/lidm.service.d
if ((dry)); then
    echo "+ install lidm/theme.conf -> /etc/systemd/system/lidm.service.d/theme.conf"
else
    dropin=$(sed "s|@HOME@|$HOME|" "$repo/lidm/theme.conf")
    printf '%s\n' "$dropin" | sudo tee /etc/systemd/system/lidm.service.d/theme.conf >/dev/null
fi
run sudo systemctl daemon-reload

# "Hyprland (quiet)" session: same Hyprland, but its startup log goes to a file instead
# of flashing on the console after login. lidm also reads /usr/local/share, which no
# package owns, and remembers the last session picked.
run sudo install -Dm755 "$repo/lidm/hyprland-quiet" /usr/local/bin/hyprland-quiet
run sudo install -Dm755 "$repo/lidm/lidm-console-font" /usr/local/bin/lidm-console-font
run sudo install -Dm644 "$repo/lidm/hyprland-quiet.desktop" /usr/local/share/wayland-sessions/hyprland-quiet.desktop

# Unit name comes from the package; fall back to the usual one
unit=$(pacman -Ql "$service_provider" 2>/dev/null | awk '/\.service$/ { n = split($2, a, "/"); print a[n]; exit }' || true)
unit=${unit:-lidm.service}

# Another display manager (e.g. SDDM from a previous setup) would clash with lidm
current_dm=$(readlink -f /etc/systemd/system/display-manager.service 2>/dev/null || true)
if [[ -n $current_dm && $(basename "$current_dm") != "$unit" ]]; then
    echo ":: disabling the current display manager: $(basename "$current_dm")"
    run sudo systemctl disable "$(basename "$current_dm")"
fi

# lidm replaces the getty on tty1. Takes effect on the next boot, so the
# current session is left alone.
run sudo systemctl disable getty@tty1.service
run sudo systemctl enable "$unit"

echo
echo "Done. Reboot to start lidm."
echo "Rollback: from another tty run: sudo systemctl disable ${unit%.service} && sudo systemctl enable getty@tty1"
